# Generated by Django 5.0.2 on 2024-02-22 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_rename_poll_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="question",
            new_name="question_text",
        ),
    ]
