# Generated by Django 5.0.2 on 2024-02-22 17:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_rename_question_question_question_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="poll",
            new_name="question",
        ),
    ]
